name: Copy Changed Files

on:
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit ID to analyze (defaults to latest)'
        required: false
        default: ''
  push:
    branches:
      - master
      - develop

jobs:
  copy-changed-files:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Copy Changed Files
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_ID: ${{ github.event.inputs.commit_id || github.sha }}
        run: |
          $sourceDir = "${{ github.workspace }}"
          $destDir = "${{ github.workspace }}/changed-files"
          
          # Create artifacts directory
          New-Item -Path $destDir -ItemType Directory -Force
          
          # Get the commit SHA
          $commitSha = "$env:COMMIT_ID"
          Write-Host "Analyzing commit: $commitSha"
          
          # Get previous commit
          $previousCommitSha = git rev-parse "$commitSha^"
          Write-Host "Previous commit: $previousCommitSha"
          
          # Get changed files between commits
          $changedFiles = git diff --name-only $previousCommitSha $commitSha
          
          $fileCount = 0
          
          foreach ($file in $changedFiles) {
            $fileCount++
            Write-Host ".....Changed File: $file"
            
            # Convert forward slashes to backslashes for Windows paths
            $filePath = $file.Replace("/", "\")
            $path = Split-Path -Path $filePath
            
            # Create directory structure
            if ($path) {
              $targetDir = "$destDir\$path"
              if (!(Test-Path -Path $targetDir)) {
                New-Item -Path $targetDir -ItemType Directory -Force
              }
            } else {
              $targetDir = $destDir
            }
            
            # Copy the file
            $sourceFile = "$sourceDir\$file"
            if (Test-Path -Path $sourceFile -PathType Leaf) {
              Write-Host "Copying File: $sourceFile to $targetDir"
              Copy-Item -Path $sourceFile -Destination $targetDir -Force
            }
          }
          
          # Create a summary file
          $summaryFile = "$destDir\change-summary.md"
          "# Changes in commit $commitSha" | Out-File -FilePath $summaryFile
          "## Previous commit: $previousCommitSha" | Out-File -FilePath $summaryFile -Append
          "## Total files changed: $fileCount" | Out-File -FilePath $summaryFile -Append
          "" | Out-File -FilePath $summaryFile -Append
          "## Changed Files:" | Out-File -FilePath $summaryFile -Append
          foreach ($file in $changedFiles) {
            "- $file" | Out-File -FilePath $summaryFile -Append
          }
          
          Write-Host "Total files copied: $fileCount" -ForegroundColor Green
          
          if ($fileCount -eq 0) {
            Write-Host "No files were changed in this commit." -ForegroundColor Yellow
          }
      
      - name: Upload Changed Files Artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-files-${{ github.sha }}
          path: ${{ github.workspace }}/changed-files/
          if-no-files-found: warn
          retention-days: 30

      - name: Add Job Summary
        shell: pwsh
        run: |
          $summaryFile = "${{ github.workspace }}/changed-files/change-summary.md"
          
          if (Test-Path -Path $summaryFile -PathType Leaf) {
            $content = Get-Content -Path $summaryFile -Raw
            
            # Output to job summary
            $content | Out-File -FilePath $env:GITHUB_STEP_SUMMARY
          } else {
            Write-Output "## No files were changed in this commit" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY
          }
