name: Detect and Copy Changed Files

on:
  push:
    branches:
      - master
      - develop

jobs:
  copy-changed-files:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List of Changed Files
        run: |
          echo "Changed Files in this Commit:"
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
        shell: bash

      - name: Copy Changed Files
        shell: pwsh
        run: |
          $sourceDir = "${{ github.workspace }}"
          $destDir = "$sourceDir\artifacts"

          # Ensure artifacts directory exists
          if (!(Test-Path -Path $destDir)) {
            New-Item -ItemType Directory -Path $destDir -Force
          }

          # Convert GitHub Actions output into an array
          $changedFilesRaw = "${{ steps.changed-files.outputs.all_changed_files }}"
          $changedFiles = $changedFilesRaw -split "`n"

          if ($changedFiles.Count -eq 0 -or $changedFiles[0] -eq '') {
            Write-Host "⚠️ No changed files detected. Skipping copy step."
            exit 0
          }

          foreach ($file in $changedFiles) {
            # Normalize file path to Windows format
            $file = $file.Trim() -replace "/", "\"

            if ($file -eq '') { continue }

            Write-Host "Processing: $file"

            $sourcePath = "$sourceDir\$file"
            $destPath = "$destDir\$file"
            $destFolder = Split-Path -Path $destPath -Parent

            if (!(Test-Path -Path $sourcePath)) {
              Write-Host "❌ Skipping non-existing file: $sourcePath"
              continue
            }

            if (!(Test-Path -Path $destFolder)) {
              New-Item -ItemType Directory -Path $destFolder -Force
            }

            Copy-Item -Path $sourcePath -Destination $destPath -Force
            Write-Host "✅ Copied: $file"
          }

          # Debug: List contents of artifacts directory
          Write-Host "📂 Contents of artifacts directory:"
          Get-ChildItem -Path $destDir -Recurse

      - name: Upload Changed Files
        uses: actions/upload-artifact@v4
        with:
          name: "changed-files-${{ github.run_id }}"
          path: ${{ github.workspace }}/artifacts/.github/workflows/copy-changed-files.yml
          if-no-files-found: error
          compression-level: 6
          overwrite: false
          include-hidden-files: false
