name: Deploy Angular App to Azure Web App
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "The environment to deploy to (e.g., dev, qa, prod)"
      app-name:
        required: true
        type: string
        description: "The name of the Azure Web App"
      slot-name:
        required: true
        type: string
        description: "The slot name to deploy to"
      artifact-name:
        required: true
        type: string
        description: "The name of the artifact to download"
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: wwwroot
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app-name }}
          slot-name: ${{ inputs.slot-name }}
          package: .

      - name: Deploy completed
        run: |
          echo "Deployment completed."
          echo "If your app is not displaying correctly, check these common issues:"
          echo "1. Verify your web app is configured for static site hosting"
          echo "2. Make sure WEBSITE_RUN_FROM_PACKAGE is set to 0 in your app settings"
