name: Deploy Angular App to Azure Web App
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "The environment to deploy to (e.g., dev, qa, prod)"
      app-name:
        required: true
        type: string
        description: "The name of the Azure Web App"
      slot-name:
        required: false
        type: string
        description: "The slot name to deploy to (optional)"
        default: "production"
        
jobs:
  deploy:
    runs-on: windows-latest
    environment:
      name: ${{ inputs.environment }}
    
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-app${{ inputs.environment == 'dev' && '2' || '' }}-${{ github.run_id }}
          path: dist
      
      - name: Download source artifact
        uses: actions/download-artifact@v4
        with:
          name: changed-source-${{ github.run_id }}
          path: changed-source
      
      - name: List changed files
        shell: pwsh
        run: |
          Write-Host "Changed files that will be deployed:"
          Get-ChildItem -Path changed-source -Recurse -File | ForEach-Object {
            Write-Host $_.FullName
          }
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ inputs.environment == 'dev' ? secrets.AZURE_CREDENTIALS_DEV : secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app-name }}
          slot-name: ${{ inputs.slot-name }}
          package: dist
      
      - name: Log deployment details
        shell: pwsh
        run: |
          Write-Host "Deployment completed to ${{ inputs.app-name }}" -ForegroundColor Green
          Write-Host "Environment: ${{ inputs.environment }}" -ForegroundColor Green
          Write-Host "Slot: ${{ inputs.slot-name }}" -ForegroundColor Green
          Write-Host "Deployment URL: https://${{ inputs.app-name }}.azurewebsites.net"
