name: Deploy Angular App to Azure Web App
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "The environment to deploy to (e.g., dev, qa, prod)"
      app-name:
        required: true
        type: string
        description: "The name of the Azure Web App"
      slot-name:
        required: false
        type: string
        description: "The slot name to deploy to (optional)"
        default: "production"
jobs:
  deploy:
    runs-on: windows-latest
    environment:
      name: ${{ inputs.environment }}
    
    steps:
      - name: Download artifact for production
        if: inputs.environment == 'production'
        uses: actions/download-artifact@v4
        with:
          name: angular-app-${{ github.run_id }}
          path: dist

      - name: Download artifact for dev
        if: inputs.environment == 'dev'
        uses: actions/download-artifact@v4 
        with: 
          name: angular-app2-${{ github.run_id }} 
          path: dist 
      
      - name: Azure Login for Production
        if: inputs.environment == 'production'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Login for Dev
        if: inputs.environment == 'dev'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app-name }}
          slot-name: ${{ inputs.slot-name }}
          package: dist
