name: Azure Web App CI/CD for Dev
on: 
  push: 
    branches: 
      - develop  # Or any branch you want to trigger the dev deployment to

jobs: 
  build: 
    uses: ./.github/workflows/build.yml 
    secrets: inherit 
     
  deploy-dev: 
    needs: build 
    uses: ./.github/workflows/deploy.yml 
    with: 
      environment: 'dev'
      app-name: 'Angular-webapp2'  # Replace with your dev Azure Web App name
    secrets: inherit
