name: File Change Logger
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - develop
      # Add other important branches here
      
jobs:
  log-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get event name
        id: event
        run: echo "name=${{ github.event_name }}" >> $GITHUB_OUTPUT
          
      - name: List PR files
        if: steps.event.outputs.name == 'pull_request'
        run: |
          echo "Files changed in PR #${{ github.event.pull_request.number }}:"
          # Rest of your PR file listing code
          
      - name: List commit files (non-merge)
        if: steps.event.outputs.name == 'push'
        run: |
          IS_MERGE=$(git rev-parse --is-merge-commit ${{ github.sha }} || echo "false")
          if [ "$IS_MERGE" != "true" ]; then
            echo "Files changed in commit ${{ github.sha }}:"
            git diff-tree --no-commit-id --name-status -r ${{ github.sha }}
          else
            echo "This is a merge commit - skipping file diff"
          fi
