name: PR Check - List Changed Files in repo
on:
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files using GitHub API
        id: changed-files
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO="${{ github.repository }}"
          
          echo "Fetching files for PR #$PR_NUMBER in $REPO"
          FILES=$(curl -s -H "Authorization: token ${{ github.token }}" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/files" | jq -r '.[] | .filename')
          
          echo "Files changed in this PR:"
          echo "$FILES"
          
          # Count files by type
          ADDED=$(curl -s -H "Authorization: token ${{ github.token }}" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/files" | jq -r '.[] | select(.status == "added") | .filename')
          MODIFIED=$(curl -s -H "Authorization: token ${{ github.token }}" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/files" | jq -r '.[] | select(.status == "modified") | .filename')
          REMOVED=$(curl -s -H "Authorization: token ${{ github.token }}" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/files" | jq -r '.[] | select(.status == "removed") | .filename')
          
          echo "### Added files:"
          if [ -z "$ADDED" ]; then echo "None"; else echo "$ADDED"; fi
          
          echo "### Modified files:"
          if [ -z "$MODIFIED" ]; then echo "None"; else echo "$MODIFIED"; fi
          
          echo "### Removed files:"
          if [ -z "$REMOVED" ]; then echo "None"; else echo "$REMOVED"; fi
          
          TOTAL_COUNT=$(echo "$FILES" | wc -l)
          echo "Total changed files: $TOTAL_COUNT"
