name: PR Check - List Changed Files
on:
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This is important to get all history for comparing changes
          
      - name: List all changed files
        run: |
          echo "Files changed in this PR:"
          git diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
          
      - name: Get and log file count
        id: file-count
        run: |
          ADDED_COUNT=$(git diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^A' | wc -l)
          MODIFIED_COUNT=$(git diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^M' | wc -l)
          DELETED_COUNT=$(git diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^D' | wc -l)
          TOTAL_COUNT=$(git diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | wc -l)
          
          echo "Added files: $ADDED_COUNT"
          echo "Modified files: $MODIFIED_COUNT"
          echo "Deleted files: $DELETED_COUNT"
          echo "Total changed files: $TOTAL_COUNT"
          
          echo "added_count=$ADDED_COUNT" >> $GITHUB_OUTPUT
          echo "modified_count=$MODIFIED_COUNT" >> $GITHUB_OUTPUT
          echo "deleted_count=$DELETED_COUNT" >> $GITHUB_OUTPUT
          echo "total_count=$TOTAL_COUNT" >> $GITHUB_OUTPUT
          
      - name: List Files by Type
        run: |
          echo "### Added files:"
          git diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^A' | cut -f2-
          
          echo "### Modified files:"
          git diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^M' | cut -f2-
          
          echo "### Deleted files:"
          git diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '^D' | cut -f2-
