name: Azure Web App CI/CD
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.yml'
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: 'production'
    secrets: inherit
    
  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'production'
      app-name: 'Angular-webapp'  # Replace with your Azure Web App name
    secrets: inherit
